### ISSUE TITLE
how can get the     'client_id': '2323547071', # This is the leaked credential of Weico

### ISSUE THREAD

**Issue by buzai** [izzyleung/Robots#1]
i think this id and key had changed

**Comment by izzyleung** [comment]
Hmm, it has been a long time since I last used Weibo's API to interact with it. Since then, lot of things happened, and I do not have a good answer for your question, sorry.

The `client_id` used in the source code was the leaked credential for Weico, which has a higher privilege than normal Weibo 3rd party client(s). This credential has been revoked by Sina, and now Weico should be using a new credential to interact with Weibo.

I would suggest that you should either use tools like Burp Suite / Fiddler to intercept the internet traffic that Weico used to get access to Weibo, or just use tools like apktools to decompile the source code of the Weico client for Android in order to get the credential.

**Comment by buzai** [comment]
I found some clues with charles，
like this
```
&aid=01 Aq3zj7I6a4mzCIoI1cMraeXeIxnZPE8igSvmQ9eV77VkkUI.

&c=weicoabroad
&from=1228493010

&getcookie=1

&i=1e d5a92
&lang=zh_CN
&p=c248wEenflf3jVGs1vU1aV5jFBDxcP8MZCh % 2 BJnnyTj3UK1cRh % 2 BeVvrGY1DdAUENLgPJ9ZHZtkHNAyJI8l9fxXo5HVrLsp5fRRpg3NpRu2jmHnjupzmxaOws6LyCDyb4mPSODDp
% 2 Bqd / D6csJhJ7LNNVj4iiS1iJo % 2 BjRirls6zVc4 % 3 D

&s=b8b5f0be
&u=17611227832

&ua=iPhone8 % 2 C1_iOS10 .3 .3 _Weico_2840_wifi
&v_p=50
```
If you remember something, and know which parameters are important to tell me, if you do not remember, then forget it. Thank you, I think you are a Chinese, because I also use Google to translate 233
